### ISSUE TITLE
Main's Makefile fails because of wrong name of asm compiler

### ISSUE THREAD

**Issue by vian96** [alexxRT/riscv64-simulator#13]
- on main branch, after makefile MR, it tries to compile program with `riscv64-elf-gcc` while my pc (wsl, ubuntu) has `riscv64-unknown-elf-gcc` which may cause problems on other similar systems
- can be fixed by  `ln -s $(which riscv64-unknown-elf-gcc) /usr/local/bin/riscv64-elf-gcc` but ideally needs better fix

**Comment by vian96** [comment]
I also changed out dir name to lowercase and made test output slightly more telling
Please use branch `hotfix-makefile`

**Comment by nerett** [comment]
Compiler name `riscv64-elf-gcc` is specific for OpenSuse Tumbleweed OSS repos
